// This file is @generated by prost-build.
/// A GetLicenseResponse is sent as the response for this.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeactivateMachinesRequest {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub machine_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
