// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct FetchProductInfoRequest {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FetchProductInfoResponse {
    #[prost(map = "string, message", tag = "1")]
    pub product_info: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ProductInfo,
    >,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProductInfo {
    #[prost(bool, tag = "1")]
    pub is_offline_allowed: bool,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub max_machines_per_license: u32,
    #[prost(string, tag = "4")]
    pub product_name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub public_key: ::prost::alloc::string::String,
}
