// This file is @generated by prost-build.
/// a Machine Database Item
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MachineDbItem {
    #[prost(string, tag = "1")]
    pub computer_name: ::prost::alloc::string::String,
}
