// This file is @generated by prost-build.
/// A store registration request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterStoreRequest {
    #[prost(string, tag = "1")]
    pub contact_first_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub contact_last_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub contact_email: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub store_name: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub store_url: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub discord_username: ::prost::alloc::string::String,
    #[prost(string, tag = "27")]
    pub state: ::prost::alloc::string::String,
    #[prost(string, tag = "29")]
    pub country: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "30")]
    pub public_signing_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "50")]
    pub timestamp: u64,
}
