// This file is @generated by prost-build.
/// store database item. This is stored in a protobuf message so that its contents can be easily encrypted. The content in the encrypted message will not be able to be analyzed with tools such as AWS Athena.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StoreDbItem {
    #[prost(string, tag = "1")]
    pub contact_first_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub contact_last_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub store_name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub store_url: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub discord_username: ::prost::alloc::string::String,
    #[prost(string, tag = "27")]
    pub state: ::prost::alloc::string::String,
    #[prost(string, tag = "29")]
    pub country: ::prost::alloc::string::String,
    /// a list of product_ids that the store is licensing to customers
    #[prost(bytes = "vec", repeated, tag = "30")]
    pub product_ids: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
