[workspace]
members = [
    "license_activation_refactor",
    "create_license_refactor",
    "create_plugin_refactor",
    "get_license_refactor",
    "register_store_refactor",
	"utils",
    "proto"
]
