cd scripting
./create_build_script.sh "register_store_refactor"
./create_build_script.sh "create_plugin_refactor"
./create_build_script.sh "create_license_refactor"
./create_build_script.sh "license_activation_refactor"
./create_build_script.sh "get_license_refactor"
./create_build_script.sh "publish_rotating_keys"
./create_build_script.sh "deactivate_machines"
./create_build_script.sh "regenerate_license_code"